---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: centos-6.6
      
suites:
  - name: default
    run_list:
      - recipe[perforce::default]
